server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_usuarios
    username: root
    password: admin


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
appDescription: "Pragma Powerup"
appVersion: "1.0.0"
